language: java

sudo: required
services:
  - docker

jobs:
  include:
    - stage: build jar
      script:
        - mvn clean test package
    - stage: build docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - mvn dockerfile:build
        - mvn dockerfile:tag@tag-version
        - mvn dockerfile:push@push-version
        - mvn dockerfile:push@push-latest