apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name:
build:
  artifacts:
    - image: ifsc-ical-generator
      jib: {}
deploy:
  helm:
    releases:
      - name: ifsc-ical-generator
        chartPath: qwyck/ifsc-ical-generator
        imageStrategy:
          helm:
            explicitRegistry: false
        remote: true
        values:
          image: ifsc-ical-generator
        valuesFiles:
          - charts/ifsc-ical-generator/values-local.yaml
