spring:
  application:
    name: ifsc-ical-generator
  cloud:
    kubernetes:
      reload:
        enabled: true
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics