name: Java CI

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    
    env: 
      SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
 
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Set up Gradle
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew build
      
    - name: Sonar
      run: ./gradlew sonarqube -Dsonar.login=${SONAR_LOGIN} -Dsonar.branch.name=$(git branch --show-current)