name: release

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'gradle.properties'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: 'false'

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up Gradle
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew build

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        extra_plugins: |
          gradle-semantic-release-plugin
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

    - name: Docker Release
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        docker login -u jrmcdonald -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        ./gradlew jib